# SPDX-License-Identifier: MIT

name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Ruff
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Ruff
        uses: chartboost/ruff-action@v1

  formatting:
    name: Black
    
    runs-on: ubuntu-latest
    needs: [linting]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        id: checkifneeded
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "~= 23.0"
        continue-on-error: true

      - name: Format
        uses: psf/black@stable
        with:
          options: "--verbose"
          version: "~= 23.0"

      - name: Create pull request
        if: steps.checkifneeded.outcome != 'success'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "ðŸŽ¨ [tuning] Resolved formatting errors"
          commit-message: "format code using psf/black"
          body: |
            Formatter errors found in: ${{ github.sha }}.
          base: ${{ github.head_ref }}
          branch: actions/black
          reviewers: hitblast
          delete-branch: true 
